language: python
addons:
  apt:
    sources:
      - deadsnakes
    packages:
      - python3.5
python:
- '2.7'
install:
- pip install tox coverage python-coveralls
script:
- tox
- coverage combine
- coverage report
after_success:
- coveralls
